/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package code.bdif.data.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Features extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Features\",\"namespace\":\"code.bdif.data.avro\",\"fields\":[{\"name\":\"filename\",\"type\":\"string\"},{\"name\":\"content\",\"type\":[\"bytes\",\"null\"]},{\"name\":\"width\",\"type\":[\"int\",\"null\"]},{\"name\":\"height\",\"type\":[\"int\",\"null\"]},{\"name\":\"depth\",\"type\":[\"int\",\"null\"]},{\"name\":\"size\",\"type\":[\"int\",\"null\"]},{\"name\":\"nChannels\",\"type\":[\"int\",\"null\"]},{\"name\":\"widthStep\",\"type\":[\"int\",\"null\"]},{\"name\":\"source\",\"type\":\"string\"},{\"name\":\"featuredata\",\"type\":[\"string\",\"null\"]},{\"name\":\"labeldesc\",\"type\":\"string\"},{\"name\":\"labelpos\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence filename;
  @Deprecated public java.nio.ByteBuffer content;
  @Deprecated public java.lang.Integer width;
  @Deprecated public java.lang.Integer height;
  @Deprecated public java.lang.Integer depth;
  @Deprecated public java.lang.Integer size;
  @Deprecated public java.lang.Integer nChannels;
  @Deprecated public java.lang.Integer widthStep;
  @Deprecated public java.lang.CharSequence source;
  @Deprecated public java.lang.CharSequence featuredata;
  @Deprecated public java.lang.CharSequence labeldesc;
  @Deprecated public java.lang.CharSequence labelpos;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public Features() {}

  /**
   * All-args constructor.
   */
  public Features(java.lang.CharSequence filename, java.nio.ByteBuffer content, java.lang.Integer width, java.lang.Integer height, java.lang.Integer depth, java.lang.Integer size, java.lang.Integer nChannels, java.lang.Integer widthStep, java.lang.CharSequence source, java.lang.CharSequence featuredata, java.lang.CharSequence labeldesc, java.lang.CharSequence labelpos) {
    this.filename = filename;
    this.content = content;
    this.width = width;
    this.height = height;
    this.depth = depth;
    this.size = size;
    this.nChannels = nChannels;
    this.widthStep = widthStep;
    this.source = source;
    this.featuredata = featuredata;
    this.labeldesc = labeldesc;
    this.labelpos = labelpos;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return filename;
    case 1: return content;
    case 2: return width;
    case 3: return height;
    case 4: return depth;
    case 5: return size;
    case 6: return nChannels;
    case 7: return widthStep;
    case 8: return source;
    case 9: return featuredata;
    case 10: return labeldesc;
    case 11: return labelpos;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: filename = (java.lang.CharSequence)value$; break;
    case 1: content = (java.nio.ByteBuffer)value$; break;
    case 2: width = (java.lang.Integer)value$; break;
    case 3: height = (java.lang.Integer)value$; break;
    case 4: depth = (java.lang.Integer)value$; break;
    case 5: size = (java.lang.Integer)value$; break;
    case 6: nChannels = (java.lang.Integer)value$; break;
    case 7: widthStep = (java.lang.Integer)value$; break;
    case 8: source = (java.lang.CharSequence)value$; break;
    case 9: featuredata = (java.lang.CharSequence)value$; break;
    case 10: labeldesc = (java.lang.CharSequence)value$; break;
    case 11: labelpos = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'filename' field.
   */
  public java.lang.CharSequence getFilename() {
    return filename;
  }

  /**
   * Sets the value of the 'filename' field.
   * @param value the value to set.
   */
  public void setFilename(java.lang.CharSequence value) {
    this.filename = value;
  }

  /**
   * Gets the value of the 'content' field.
   */
  public java.nio.ByteBuffer getContent() {
    return content;
  }

  /**
   * Sets the value of the 'content' field.
   * @param value the value to set.
   */
  public void setContent(java.nio.ByteBuffer value) {
    this.content = value;
  }

  /**
   * Gets the value of the 'width' field.
   */
  public java.lang.Integer getWidth() {
    return width;
  }

  /**
   * Sets the value of the 'width' field.
   * @param value the value to set.
   */
  public void setWidth(java.lang.Integer value) {
    this.width = value;
  }

  /**
   * Gets the value of the 'height' field.
   */
  public java.lang.Integer getHeight() {
    return height;
  }

  /**
   * Sets the value of the 'height' field.
   * @param value the value to set.
   */
  public void setHeight(java.lang.Integer value) {
    this.height = value;
  }

  /**
   * Gets the value of the 'depth' field.
   */
  public java.lang.Integer getDepth() {
    return depth;
  }

  /**
   * Sets the value of the 'depth' field.
   * @param value the value to set.
   */
  public void setDepth(java.lang.Integer value) {
    this.depth = value;
  }

  /**
   * Gets the value of the 'size' field.
   */
  public java.lang.Integer getSize() {
    return size;
  }

  /**
   * Sets the value of the 'size' field.
   * @param value the value to set.
   */
  public void setSize(java.lang.Integer value) {
    this.size = value;
  }

  /**
   * Gets the value of the 'nChannels' field.
   */
  public java.lang.Integer getNChannels() {
    return nChannels;
  }

  /**
   * Sets the value of the 'nChannels' field.
   * @param value the value to set.
   */
  public void setNChannels(java.lang.Integer value) {
    this.nChannels = value;
  }

  /**
   * Gets the value of the 'widthStep' field.
   */
  public java.lang.Integer getWidthStep() {
    return widthStep;
  }

  /**
   * Sets the value of the 'widthStep' field.
   * @param value the value to set.
   */
  public void setWidthStep(java.lang.Integer value) {
    this.widthStep = value;
  }

  /**
   * Gets the value of the 'source' field.
   */
  public java.lang.CharSequence getSource() {
    return source;
  }

  /**
   * Sets the value of the 'source' field.
   * @param value the value to set.
   */
  public void setSource(java.lang.CharSequence value) {
    this.source = value;
  }

  /**
   * Gets the value of the 'featuredata' field.
   */
  public java.lang.CharSequence getFeaturedata() {
    return featuredata;
  }

  /**
   * Sets the value of the 'featuredata' field.
   * @param value the value to set.
   */
  public void setFeaturedata(java.lang.CharSequence value) {
    this.featuredata = value;
  }

  /**
   * Gets the value of the 'labeldesc' field.
   */
  public java.lang.CharSequence getLabeldesc() {
    return labeldesc;
  }

  /**
   * Sets the value of the 'labeldesc' field.
   * @param value the value to set.
   */
  public void setLabeldesc(java.lang.CharSequence value) {
    this.labeldesc = value;
  }

  /**
   * Gets the value of the 'labelpos' field.
   */
  public java.lang.CharSequence getLabelpos() {
    return labelpos;
  }

  /**
   * Sets the value of the 'labelpos' field.
   * @param value the value to set.
   */
  public void setLabelpos(java.lang.CharSequence value) {
    this.labelpos = value;
  }

  /** Creates a new Features RecordBuilder */
  public static code.bdif.data.avro.Features.Builder newBuilder() {
    return new code.bdif.data.avro.Features.Builder();
  }
  
  /** Creates a new Features RecordBuilder by copying an existing Builder */
  public static code.bdif.data.avro.Features.Builder newBuilder(code.bdif.data.avro.Features.Builder other) {
    return new code.bdif.data.avro.Features.Builder(other);
  }
  
  /** Creates a new Features RecordBuilder by copying an existing Features instance */
  public static code.bdif.data.avro.Features.Builder newBuilder(code.bdif.data.avro.Features other) {
    return new code.bdif.data.avro.Features.Builder(other);
  }
  
  /**
   * RecordBuilder for Features instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Features>
    implements org.apache.avro.data.RecordBuilder<Features> {

    private java.lang.CharSequence filename;
    private java.nio.ByteBuffer content;
    private java.lang.Integer width;
    private java.lang.Integer height;
    private java.lang.Integer depth;
    private java.lang.Integer size;
    private java.lang.Integer nChannels;
    private java.lang.Integer widthStep;
    private java.lang.CharSequence source;
    private java.lang.CharSequence featuredata;
    private java.lang.CharSequence labeldesc;
    private java.lang.CharSequence labelpos;

    /** Creates a new Builder */
    private Builder() {
      super(code.bdif.data.avro.Features.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(code.bdif.data.avro.Features.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.filename)) {
        this.filename = data().deepCopy(fields()[0].schema(), other.filename);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.content)) {
        this.content = data().deepCopy(fields()[1].schema(), other.content);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.width)) {
        this.width = data().deepCopy(fields()[2].schema(), other.width);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.height)) {
        this.height = data().deepCopy(fields()[3].schema(), other.height);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.depth)) {
        this.depth = data().deepCopy(fields()[4].schema(), other.depth);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.size)) {
        this.size = data().deepCopy(fields()[5].schema(), other.size);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.nChannels)) {
        this.nChannels = data().deepCopy(fields()[6].schema(), other.nChannels);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.widthStep)) {
        this.widthStep = data().deepCopy(fields()[7].schema(), other.widthStep);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.source)) {
        this.source = data().deepCopy(fields()[8].schema(), other.source);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.featuredata)) {
        this.featuredata = data().deepCopy(fields()[9].schema(), other.featuredata);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.labeldesc)) {
        this.labeldesc = data().deepCopy(fields()[10].schema(), other.labeldesc);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.labelpos)) {
        this.labelpos = data().deepCopy(fields()[11].schema(), other.labelpos);
        fieldSetFlags()[11] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Features instance */
    private Builder(code.bdif.data.avro.Features other) {
            super(code.bdif.data.avro.Features.SCHEMA$);
      if (isValidValue(fields()[0], other.filename)) {
        this.filename = data().deepCopy(fields()[0].schema(), other.filename);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.content)) {
        this.content = data().deepCopy(fields()[1].schema(), other.content);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.width)) {
        this.width = data().deepCopy(fields()[2].schema(), other.width);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.height)) {
        this.height = data().deepCopy(fields()[3].schema(), other.height);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.depth)) {
        this.depth = data().deepCopy(fields()[4].schema(), other.depth);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.size)) {
        this.size = data().deepCopy(fields()[5].schema(), other.size);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.nChannels)) {
        this.nChannels = data().deepCopy(fields()[6].schema(), other.nChannels);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.widthStep)) {
        this.widthStep = data().deepCopy(fields()[7].schema(), other.widthStep);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.source)) {
        this.source = data().deepCopy(fields()[8].schema(), other.source);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.featuredata)) {
        this.featuredata = data().deepCopy(fields()[9].schema(), other.featuredata);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.labeldesc)) {
        this.labeldesc = data().deepCopy(fields()[10].schema(), other.labeldesc);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.labelpos)) {
        this.labelpos = data().deepCopy(fields()[11].schema(), other.labelpos);
        fieldSetFlags()[11] = true;
      }
    }

    /** Gets the value of the 'filename' field */
    public java.lang.CharSequence getFilename() {
      return filename;
    }
    
    /** Sets the value of the 'filename' field */
    public code.bdif.data.avro.Features.Builder setFilename(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.filename = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'filename' field has been set */
    public boolean hasFilename() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'filename' field */
    public code.bdif.data.avro.Features.Builder clearFilename() {
      filename = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'content' field */
    public java.nio.ByteBuffer getContent() {
      return content;
    }
    
    /** Sets the value of the 'content' field */
    public code.bdif.data.avro.Features.Builder setContent(java.nio.ByteBuffer value) {
      validate(fields()[1], value);
      this.content = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'content' field has been set */
    public boolean hasContent() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'content' field */
    public code.bdif.data.avro.Features.Builder clearContent() {
      content = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'width' field */
    public java.lang.Integer getWidth() {
      return width;
    }
    
    /** Sets the value of the 'width' field */
    public code.bdif.data.avro.Features.Builder setWidth(java.lang.Integer value) {
      validate(fields()[2], value);
      this.width = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'width' field has been set */
    public boolean hasWidth() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'width' field */
    public code.bdif.data.avro.Features.Builder clearWidth() {
      width = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'height' field */
    public java.lang.Integer getHeight() {
      return height;
    }
    
    /** Sets the value of the 'height' field */
    public code.bdif.data.avro.Features.Builder setHeight(java.lang.Integer value) {
      validate(fields()[3], value);
      this.height = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'height' field has been set */
    public boolean hasHeight() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'height' field */
    public code.bdif.data.avro.Features.Builder clearHeight() {
      height = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'depth' field */
    public java.lang.Integer getDepth() {
      return depth;
    }
    
    /** Sets the value of the 'depth' field */
    public code.bdif.data.avro.Features.Builder setDepth(java.lang.Integer value) {
      validate(fields()[4], value);
      this.depth = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'depth' field has been set */
    public boolean hasDepth() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'depth' field */
    public code.bdif.data.avro.Features.Builder clearDepth() {
      depth = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'size' field */
    public java.lang.Integer getSize() {
      return size;
    }
    
    /** Sets the value of the 'size' field */
    public code.bdif.data.avro.Features.Builder setSize(java.lang.Integer value) {
      validate(fields()[5], value);
      this.size = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'size' field has been set */
    public boolean hasSize() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'size' field */
    public code.bdif.data.avro.Features.Builder clearSize() {
      size = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'nChannels' field */
    public java.lang.Integer getNChannels() {
      return nChannels;
    }
    
    /** Sets the value of the 'nChannels' field */
    public code.bdif.data.avro.Features.Builder setNChannels(java.lang.Integer value) {
      validate(fields()[6], value);
      this.nChannels = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'nChannels' field has been set */
    public boolean hasNChannels() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'nChannels' field */
    public code.bdif.data.avro.Features.Builder clearNChannels() {
      nChannels = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'widthStep' field */
    public java.lang.Integer getWidthStep() {
      return widthStep;
    }
    
    /** Sets the value of the 'widthStep' field */
    public code.bdif.data.avro.Features.Builder setWidthStep(java.lang.Integer value) {
      validate(fields()[7], value);
      this.widthStep = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'widthStep' field has been set */
    public boolean hasWidthStep() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'widthStep' field */
    public code.bdif.data.avro.Features.Builder clearWidthStep() {
      widthStep = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'source' field */
    public java.lang.CharSequence getSource() {
      return source;
    }
    
    /** Sets the value of the 'source' field */
    public code.bdif.data.avro.Features.Builder setSource(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.source = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'source' field has been set */
    public boolean hasSource() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'source' field */
    public code.bdif.data.avro.Features.Builder clearSource() {
      source = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'featuredata' field */
    public java.lang.CharSequence getFeaturedata() {
      return featuredata;
    }
    
    /** Sets the value of the 'featuredata' field */
    public code.bdif.data.avro.Features.Builder setFeaturedata(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.featuredata = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'featuredata' field has been set */
    public boolean hasFeaturedata() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'featuredata' field */
    public code.bdif.data.avro.Features.Builder clearFeaturedata() {
      featuredata = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'labeldesc' field */
    public java.lang.CharSequence getLabeldesc() {
      return labeldesc;
    }
    
    /** Sets the value of the 'labeldesc' field */
    public code.bdif.data.avro.Features.Builder setLabeldesc(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.labeldesc = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'labeldesc' field has been set */
    public boolean hasLabeldesc() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'labeldesc' field */
    public code.bdif.data.avro.Features.Builder clearLabeldesc() {
      labeldesc = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'labelpos' field */
    public java.lang.CharSequence getLabelpos() {
      return labelpos;
    }
    
    /** Sets the value of the 'labelpos' field */
    public code.bdif.data.avro.Features.Builder setLabelpos(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.labelpos = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'labelpos' field has been set */
    public boolean hasLabelpos() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'labelpos' field */
    public code.bdif.data.avro.Features.Builder clearLabelpos() {
      labelpos = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    public Features build() {
      try {
        Features record = new Features();
        record.filename = fieldSetFlags()[0] ? this.filename : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.content = fieldSetFlags()[1] ? this.content : (java.nio.ByteBuffer) defaultValue(fields()[1]);
        record.width = fieldSetFlags()[2] ? this.width : (java.lang.Integer) defaultValue(fields()[2]);
        record.height = fieldSetFlags()[3] ? this.height : (java.lang.Integer) defaultValue(fields()[3]);
        record.depth = fieldSetFlags()[4] ? this.depth : (java.lang.Integer) defaultValue(fields()[4]);
        record.size = fieldSetFlags()[5] ? this.size : (java.lang.Integer) defaultValue(fields()[5]);
        record.nChannels = fieldSetFlags()[6] ? this.nChannels : (java.lang.Integer) defaultValue(fields()[6]);
        record.widthStep = fieldSetFlags()[7] ? this.widthStep : (java.lang.Integer) defaultValue(fields()[7]);
        record.source = fieldSetFlags()[8] ? this.source : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.featuredata = fieldSetFlags()[9] ? this.featuredata : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.labeldesc = fieldSetFlags()[10] ? this.labeldesc : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.labelpos = fieldSetFlags()[11] ? this.labelpos : (java.lang.CharSequence) defaultValue(fields()[11]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
